version: '2.1'
services:
    postgres:
        build: ./dockerfiles/postgres/Dockerfile
        volumes:
            - 
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        healthcheck:
            test: 
    airflow:
        image: centos:latest
        restart: always
        depends_on:
            - postgres
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"